### ISSUE TITLE
The build structure does not work with Docker

### ISSUE THREAD

**Issue by yohanswanepoel** [snowjet/DaaC#1]
johan-bigmac:docker johanswanepoel$ docker build -f ./DaaC/noVNC/Dockerfile .
Sending build context to Docker daemon  243.2kB
Step 1/14 : FROM centos:7
 ---> 9f38484d220f
Step 2/14 : ENV container docker
 ---> Using cache
 ---> 0e22f8f97af0
Step 3/14 : ENV IPA_SERVER=""     LDAP_BASEDN=""     LOCAL_AUTH_USER=""     LOCAL_AUTH_USER_PWHASH=""     NFS_HOMEDIR_SEVER=""
 ---> Using cache
 ---> 3a713def5acb
Step 4/14 : SHELL ["/bin/bash", "-c"]
 ---> Using cache
 ---> ee4b4d5911d9
Step 5/14 : ADD ../common/scripts/ /tmp/
ADD failed: Forbidden path outside the build context: ../common/scripts/ ()
johan-bigmac:docker johanswanepoel$ docker build -f ./DaaC/noVNC/Dockerfile .
Sending build context to Docker daemon  243.2kB
Step 1/14 : FROM centos:7
 ---> 9f38484d220f
Step 2/14 : ENV container docker
 ---> Using cache
 ---> 0e22f8f97af0
Step 3/14 : ENV IPA_SERVER=""     LDAP_BASEDN=""     LOCAL_AUTH_USER="johan"     LOCAL_AUTH_USER_PWHASH="Passw0rd123"     NFS_HOMEDIR_SEVER=""
 ---> Using cache
 ---> 3a713def5acb
Step 4/14 : SHELL ["/bin/bash", "-c"]
 ---> Using cache
 ---> ee4b4d5911d9
Step 5/14 : ADD ../common/scripts/ /tmp/
ADD failed: Forbidden path outside the build context: ../common/scripts/ ()

**Comment by snowjet** [comment]
You need to build within the path. You also need to set the password as a hash.
