### ISSUE TITLE
Running on OpenShift - Permission Denied /supervisord.log

### ISSUE THREAD

**Issue by yohanswanepoel** [snowjet/DaaC#7]
| Traceback (most recent call last):
-- | --
  | File "/usr/bin/supervisord", line 9, in <module>
  | load_entry_point('supervisor==3.1.4', 'console_scripts', 'supervisord')()
  | File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 366, in main
  | go(options)
  | File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 376, in go
  | d.main()
  | File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 77, in main
  | info_messages)
  | File "/usr/lib/python2.7/site-packages/supervisor/options.py", line 1329, in make_logger
  | stdout = self.nodaemon,
  | File "/usr/lib/python2.7/site-packages/supervisor/loggers.py", line 346, in getLogger
  | handlers.append(RotatingFileHandler(filename,'a',maxbytes,backups))
  | File "/usr/lib/python2.7/site-packages/supervisor/loggers.py", line 172, in __init__
  | FileHandler.__init__(self, filename, mode)
  | File "/usr/lib/python2.7/site-packages/supervisor/loggers.py", line 98, in __init__
  | self.stream = open(filename, mode)
  | IOError: [Errno 13] Permission denied: '/supervisord.log'

**Comment by snowjet** [comment]
This should now be fixed with the correct permissions on the logging directory.
